FROM prestaclaude/prestashop:1.7.6.3-fpm

COPY pre-install-scripts/* /tmp/pre-install-scripts/
COPY post-install-scripts/* /tmp/post-install-scripts/
COPY init-scripts/* /tmp/init-scripts/

COPY --chown=www-data:www-data fixtures-10 /opt/fixtures-10
COPY --chown=www-data:www-data fixtures-1000 /opt/fixtures-1000

#RUN sed -i 's/dynamic/static/g' /usr/local/etc/php-fpm.d/*
#RUN sed -i 's/^pm.start_servers\ =\ 2/pm.start_servers = 15/g' /usr/local/etc/php-fpm.d/*
#RUN sed -i 's/^pm.max_spare_servers\ =\ 3/pm.max_spare_servers = 0/g' /usr/local/etc/php-fpm.d/*
#RUN sed -i 's/^pm.min_spare_servers\ =\ 1/pm.min_spare_servers = 0/g' /usr/local/etc/php-fpm.d/*
#RUN sed -i 's/pm.max_children\ =\ 5/pm.max_children\ =\ 15/g' /usr/local/etc/php-fpm.d/*
